### ISSUE TITLE
[Bug] Issue with Time Period Function in Permissions

### ISSUE THREAD

**Issue by lberrezoug** [jumpserver/jumpserver#12482] opened 2024-01-02 11:00 UTC
**JumpServe v3.10.1 **

**Firefox 121.0**

**Bug**

I hope this message finds you well. I wanted to bring to your attention an issue I encountered in the permissions section, specifically in "User Login ACL," when using the Time Period function.

In detail, once I select a time slot in the table and click "Submit," when I reopen the rule in question, I notice that the saved time slot does not match the one I selected. I invite you to check the attached video for more details.

Additionally, I observed after several attempts that the time 3 AM seems to actually represent 7 PM, at least in terms of the display in the table. However, I am unsure of the value that is actually being considered.

Thank you for your attention to this issue, and I hope it will be resolved soon.

**Bug 重现步骤(有截图更好)**
1. Navigate to the "Permissions" section in the interface
2. Select "User Login ACL."
3. Use the "Time Period" function to set a specific time slot.
4. In the table, choose a time slot and click "Submit" to save the changes.
5. Reopen the rule in question and check if the saved time slot matches the one you selected.
6. Repeat these steps with different time slots to observe the consistency of the recordings.

https://github.com/jumpserver/jumpserver/assets/48010763/7e11cc10-1ca5-40af-b29b-2b3d7c3727a8

**Comment by BaiJiangJie** [comment] 2024-01-03 02:29
<img width="1437" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/e5581f83-683a-4e3a-b017-6d48ad1a87f4">

OK, thank you for your question, but it seems that the video was not uploaded successfully.

I just tested it and it seems to be fine.

What time zone are you using? I think it's a bit of a time zone issue.

**Comment by lberrezoug** [comment] 2024-01-03 11:19
Hi BaiJiangJie, 

Guess what? I hit the send button before the file was fully loaded 😅
Anyway, just wanted to give you the lowdown on our time zone – it's GMT+1 in Algeria.

Cheers,

https://github.com/jumpserver/jumpserver/assets/48010763/7e11cc10-1ca5-40af-b29b-2b3d7c3727a8

**Comment by BaiJiangJie** [comment] 2024-01-08 09:39
Can you help me find out the exact time zone? 
[In this list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)

For example, JumpServer's default time zone is Asia/Shanghai.

**Comment by BaiJiangJie** [comment] 2024-01-08 09:56
Yes, I saw the video and there is a problem.

I changed the time zone to: `Africa/Algiers`. Still haven't reproduced the problem.

When you submit the page, take a look at the API call parameters in the browser console, including: API address and submitted parameter information.

**Comment by lberrezoug** [comment] 2024-01-09 17:13
Hi, 

Apologies for my delayed response. Indeed, my time zone is Africa/Algiers. Regarding your latest request, I'm not sure if I understood it correctly, but here are the screenshots for the PUT query. 

For your information, I selected the time range from 7 AM to 5 PM, but it seems that's not reflected in the query; the observed value is '01:00~11:00'."

![01](https://github.com/jumpserver/jumpserver/assets/48010763/1b0fc8d1-7a9f-409a-86f0-47bac31b418f)
![03](https://github.com/jumpserver/jumpserver/assets/48010763/1daef08b-f939-4142-ba78-34410691cd09)
![02](https://github.com/jumpserver/jumpserver/assets/48010763/f1779c2b-c8b3-4461-aa8c-f1011a3ac917)

**Comment by BaiJiangJie** [comment] 2024-01-11 09:46
Yes, we probably know where the problem is. It should be the browser time zone that the front end does not consider when processing time.

It is planned to be fixed in a later version.

Thank you for your submission.

**Comment by BaiJiangJie** [comment] 2024-01-11 09:51
Hi! 

May I ask which country you are from? 

We are planning to devote a considerable amount of effort to support users outside of mainland China. 

For this purpose, we have created a service and channel on the Discord platform specifically for handling user questions. 

You can join us there to discuss any questions you may have.

[Discord channel](https://discord.gg/JZZZc6XB)

**Comment by BaiJiangJie** [comment] 2024-01-15 06:59
https://github.com/jumpserver/lina/pull/3684

Fixed, v3.10.2 will be released.

@lberrezoug

**Comment by lberrezoug** [comment] 2024-01-15 11:01
> Hi! 
> 
> 
> 
> May I ask which country you are from? 
> 
> 
> 
> We are planning to devote a considerable amount of effort to support users outside of mainland China. 
> 
> 
> 
> For this purpose, we have created a service and channel on the Discord platform specifically for handling user questions. 
> 
> 
> 
> You can join us there to discuss any questions you may have.
> 
> 
> 
> [Click to join Discord channel](https://discord.gg/JZZZc6XB)
> 
> 
> 
> https://github.com/jumpserver/jumpserver/issues/12510


Hi, 
I truly appreciate the efforts you're putting into supporting all users. Regarding your question, I reside in Algeria 🇩🇿 😁 , and I’m already registered on the channel; I noticed it through one of the tickets mentioning the Discord channel, so I didn’t hesitate to join.
Best regards.

**Comment by BaiJiangJie** [comment] 2024-01-16 03:23
That's great! 

In the future, we can communicate directly on Discord for minor issues. 
For more complex problems or those with recording significance, we can discuss them in the issues section.

**Comment by jym503558564** [comment] 2024-01-18 02:13
v3.10.2-lts has been fixed, please upgrade to the latest version for validation.

**Closed by jym503558564** 2024-01-18 02:13 UTC
Labels: 类型:Bug, 状态:已完成, 状态:待反馈, 状态:待发布, 版本:v3.10.2
